# MyFabmesh.AI Cloud — Prod setup automation (PowerShell, Windows).
#
# Interactive script: prompts you for each external service's keys,
# writes them to .env.local, then runs:
#   1. Supabase SQL push (apply schema.sql via psql)
#   2. Stripe products list verification
#   3. Cloudflare Pages deploy via wrangler
#
# Run from cloud/ directory:
#   .\scripts\setup-prod.ps1
#
# To bail at any step: Ctrl+C. The .env.local is overwritten only at the end,
# so a half-done run leaves your current dev env intact.

$ErrorActionPreference = 'Stop'

Write-Host ''
Write-Host '┌─ MyFabmesh.AI Cloud — PROD setup ──────────────────────' -ForegroundColor Cyan
Write-Host '│ I will ask you for the keys from your 3 external services.'
Write-Host '│ Press Enter to use the current value in .env.local (if any).'
Write-Host '└────────────────────────────────────────────────────────'
Write-Host ''

function Ask([string]$Label, [string]$Current = '', [bool]$Secret = $false) {
    if ($Current) {
        $masked = if ($Secret) { ('*' * 6) + $Current.Substring([Math]::Max(0, $Current.Length - 4)) } else { $Current }
        Write-Host "  $Label (actuel: $masked)" -NoNewline -ForegroundColor Yellow
    } else {
        Write-Host "  $Label" -NoNewline -ForegroundColor Yellow
    }
    Write-Host ' >' -NoNewline -ForegroundColor White
    $v = Read-Host
    if ([string]::IsNullOrWhiteSpace($v)) { return $Current } else { return $v }
}

# Read current .env.local if it exists
$envPath = Join-Path $PSScriptRoot '..\.env.local'
$current = @{}
if (Test-Path $envPath) {
    Get-Content $envPath | ForEach-Object {
        if ($_ -match '^([^=]+)=(.*)$') { $current[$Matches[1]] = $Matches[2] }
    }
}

# Step 1 — Supabase
Write-Host ''
Write-Host '─── 1/3 Supabase ───────────────────────────────────' -ForegroundColor Green
Write-Host 'Dashboard: https://supabase.com/dashboard → ton projet → Settings → API'
$SUPABASE_URL = Ask 'NEXT_PUBLIC_SUPABASE_URL' $current['NEXT_PUBLIC_SUPABASE_URL']
$SUPABASE_ANON = Ask 'NEXT_PUBLIC_SUPABASE_ANON_KEY' $current['NEXT_PUBLIC_SUPABASE_ANON_KEY'] $true
$SUPABASE_SERVICE = Ask 'SUPABASE_SERVICE_ROLE_KEY' $current['SUPABASE_SERVICE_ROLE_KEY'] $true

# Step 2 — Stripe
Write-Host ''
Write-Host '─── 2/3 Stripe ────────────────────────────────────' -ForegroundColor Green
Write-Host 'Dashboard: https://dashboard.stripe.com/test/apikeys'
$STRIPE_SECRET = Ask 'STRIPE_SECRET_KEY (sk_test_… ou sk_live_…)' $current['STRIPE_SECRET_KEY'] $true
$STRIPE_PUB = Ask 'NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY (pk_…)' $current['NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY'] $true
Write-Host '  Webhook secret : configure dashboard → Developers → Webhooks → Add endpoint'
Write-Host '  URL : <ton-site>/api/stripe-webhook · Event : checkout.session.completed'
$STRIPE_WEBHOOK = Ask 'STRIPE_WEBHOOK_SECRET (whsec_…)' $current['STRIPE_WEBHOOK_SECRET'] $true

# Step 3 — Replicate
Write-Host ''
Write-Host '─── 3/3 Replicate (déjà OK normalement) ─────────────' -ForegroundColor Green
$REPLICATE = Ask 'REPLICATE_API_TOKEN (r8_…)' $current['REPLICATE_API_TOKEN'] $true
$REPLICATE_MODEL = Ask 'REPLICATE_MODEL (fishwowater/trellis2 si pas encore push notre Cog)' ($current['REPLICATE_MODEL'] ? $current['REPLICATE_MODEL'] : 'fishwowater/trellis2')

# Step 4 — Cloudflare R2 (optional)
Write-Host ''
Write-Host '─── 4/4 Cloudflare R2 (optionnel, skippable) ───────' -ForegroundColor Green
Write-Host 'Si tu skippes, on garde les URLs Replicate (expirent 24h, OK pour démarrer)'
$skipR2 = Read-Host '  Skip R2 ? (y/N)'
if ($skipR2 -ne 'y') {
    $R2_ACCT = Ask 'R2_ACCOUNT_ID' $current['R2_ACCOUNT_ID']
    $R2_KEY = Ask 'R2_ACCESS_KEY_ID' $current['R2_ACCESS_KEY_ID'] $true
    $R2_SECRET = Ask 'R2_SECRET_ACCESS_KEY' $current['R2_SECRET_ACCESS_KEY'] $true
    $R2_BUCKET = Ask 'R2_BUCKET' (if ($current['R2_BUCKET']) { $current['R2_BUCKET'] } else { 'myfabmesh-meshes' })
    $R2_PUBLIC = Ask 'R2_PUBLIC_URL (https://pub-xxx.r2.dev)' $current['R2_PUBLIC_URL']
} else {
    $R2_ACCT = ''; $R2_KEY = ''; $R2_SECRET = ''; $R2_BUCKET = ''; $R2_PUBLIC = ''
}

# Site URL
Write-Host ''
$SITE = Ask 'NEXT_PUBLIC_SITE_URL (https://myfabmesh-cloud.pages.dev ou ton domaine)' $current['NEXT_PUBLIC_SITE_URL']

# Write .env.local
$envContent = @"
# Generated by setup-prod.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm')
# MOCK off — using real Supabase / Stripe / Replicate / R2
MOCK=0
NEXT_PUBLIC_MOCK=0

NEXT_PUBLIC_SITE_URL=$SITE

REPLICATE_API_TOKEN=$REPLICATE
REPLICATE_MODEL=$REPLICATE_MODEL

NEXT_PUBLIC_SUPABASE_URL=$SUPABASE_URL
NEXT_PUBLIC_SUPABASE_ANON_KEY=$SUPABASE_ANON
SUPABASE_SERVICE_ROLE_KEY=$SUPABASE_SERVICE

STRIPE_SECRET_KEY=$STRIPE_SECRET
NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=$STRIPE_PUB
STRIPE_WEBHOOK_SECRET=$STRIPE_WEBHOOK

R2_ACCOUNT_ID=$R2_ACCT
R2_ACCESS_KEY_ID=$R2_KEY
R2_SECRET_ACCESS_KEY=$R2_SECRET
R2_BUCKET=$R2_BUCKET
R2_PUBLIC_URL=$R2_PUBLIC
"@
$envContent | Set-Content -Path $envPath -Encoding utf8 -NoNewline
Write-Host ''
Write-Host "  ✓ .env.local écrit ($envPath)" -ForegroundColor Green

# Rebuild
Write-Host ''
Write-Host '─── Rebuild Next.js avec les nouvelles clés ────────' -ForegroundColor Green
Push-Location (Join-Path $PSScriptRoot '..')
try {
    & npx next build
    if ($LASTEXITCODE -ne 0) { throw 'Build failed' }
    Write-Host ''
    Write-Host '✓ Build OK — prêt pour deploy' -ForegroundColor Green
    Write-Host ''
    Write-Host 'Prochaines étapes :' -ForegroundColor Cyan
    Write-Host '  1. Lance le schema Supabase : ouvre supabase.com/dashboard/project/_/sql/new'
    Write-Host '     et colle le contenu de cloud/sql/schema.sql, puis Run.'
    Write-Host '  2. Déploie sur Cloudflare Pages :'
    Write-Host '       npx wrangler login                     # une fois'
    Write-Host '       npm run pages:build && npm run pages:deploy'
    Write-Host '  3. Dans Stripe dashboard, configure le webhook :'
    Write-Host '     URL = <ton-site>/api/stripe-webhook'
    Write-Host '     Event = checkout.session.completed'
    Write-Host '     Copie le signing secret -> relance ce script pour le réintégrer'
} finally {
    Pop-Location
}
