const { contextBridge, ipcRenderer } = require('electron');

// ----------------------------------------------------------
// Test/Control API bridge
// ----------------------------------------------------------
// Minimal ipc bridge used by src/renderer/test_api_client.js so
// the external HTTP control server (src/main/test_api.js) can
// dispatch commands into the renderer. Only whitelisted channels
// are allowed; this is safe to ship even in prod because nothing
// happens unless the renderer client decides to hook in.
const _TEST_ALLOWED_SEND = new Set(['test:result', 'test:console', 'test:state-push']);
const _TEST_ALLOWED_ON   = new Set(['test:command']);
contextBridge.exposeInMainWorld('__fabmeshTest', {
  send: (channel, payload) => {
    if (_TEST_ALLOWED_SEND.has(channel)) ipcRenderer.send(channel, payload);
  },
  on: (channel, cb) => {
    if (_TEST_ALLOWED_ON.has(channel)) {
      ipcRenderer.on(channel, (_e, msg) => { try { cb(msg); } catch (_) {} });
    }
  }
});

contextBridge.exposeInMainWorld('meshyAPI', {
  generateFromPrompt: (opts) => ipcRenderer.invoke('generate-from-prompt', opts),
  generateFromImage: (opts) => ipcRenderer.invoke('generate-from-image', opts),
  generateImages: (opts) => ipcRenderer.invoke('generate-images', opts),
  generateBuildStages: (opts) => ipcRenderer.invoke('generate-build-stages', opts),
  imageToTrellis: (opts) => ipcRenderer.invoke('image-to-3d-trellis', opts),
  imageTo3D: (opts) => ipcRenderer.invoke('image-to-3d', opts),
  onAI3DProgress: (cb) => ipcRenderer.on('ai3d-progress', (e, msg) => cb(msg)),
  onBuildStageProgress: (cb) => ipcRenderer.on('build-stage-progress', (e, data) => cb(data)),
  refineMesh: (opts) => ipcRenderer.invoke('refine-mesh', opts),
  saveScreenshot: (opts) => ipcRenderer.invoke('save-screenshot', opts),
  getVersions: (name) => ipcRenderer.invoke('get-versions', name),
  revertToVersion: (opts) => ipcRenderer.invoke('revert-to-version', opts),
  listProjects: () => ipcRenderer.invoke('list-projects'),
  connectClaudeDesktop: () => ipcRenderer.invoke('connect-claude-desktop'),
  disconnectClaudeDesktop: () => ipcRenderer.invoke('disconnect-claude-desktop'),
  checkClaudeDesktop: () => ipcRenderer.invoke('check-claude-desktop'),
  onMcpJobStart: (cb) => ipcRenderer.on('mcp-job-start', (e, data) => cb(data)),
  onMcpJobEnd: (cb) => ipcRenderer.on('mcp-job-end', (e, data) => cb(data)),
  onMcpRefresh: (cb) => ipcRenderer.on('mcp-refresh', (e, data) => cb(data)),
  getConfig: () => ipcRenderer.invoke('get-config'),
  getControlApiToken: () => ipcRenderer.invoke('get-control-api-token'),
  setConfig: (patch) => ipcRenderer.invoke('set-config', patch),
  testMeshyKey: (apiKey) => ipcRenderer.invoke('test-meshy-key', apiKey),
  setBlenderPath: () => ipcRenderer.invoke('set-blender-path'),
  runBlenderScript: (opts) => ipcRenderer.invoke('run-blender-script', opts),
  openInBlender: (opts) => ipcRenderer.invoke('open-in-blender', opts),
  listMeshes: () => ipcRenderer.invoke('list-meshes'),
  getMeshPath: (filename) => ipcRenderer.invoke('get-mesh-path', filename),
  deleteMesh: (filename) => ipcRenderer.invoke('delete-mesh', filename),
  openMeshesFolder: () => ipcRenderer.invoke('open-meshes-folder'),
  openImagesFolder: () => ipcRenderer.invoke('open-images-folder'),
  listImageFolders: () => ipcRenderer.invoke('list-image-folders'),
  readMeshFile: (filePath) => ipcRenderer.invoke('read-mesh-file', filePath),
  getMeshLocalUrl: (filePath) => ipcRenderer.invoke('get-mesh-local-url', filePath),
  exportMesh: (opts) => ipcRenderer.invoke('export-mesh', opts),
  exportImage: (opts) => ipcRenderer.invoke('export-image', opts),
  pickExportPath: (opts) => ipcRenderer.invoke('pick-export-path', opts),
  getFileInfo: (filePath) => ipcRenderer.invoke('get-file-info', filePath),
  importMesh: () => ipcRenderer.invoke('import-mesh'),
  meshTool: (opts) => ipcRenderer.invoke('mesh-tool', opts),
  alignTexture: (opts) => ipcRenderer.invoke('mesh:align-texture', opts),
  saveBuffer: (opts) => ipcRenderer.invoke('save-buffer', opts),
  logToFile: (line) => ipcRenderer.send('renderer-log', line),
  generateMultiview: (opts) => ipcRenderer.invoke('generate-multiview', opts),
  checkMultiviewDir: (imagePath) => ipcRenderer.invoke('check-multiview-dir', imagePath),
  copyMeshToProject: (srcPath) => ipcRenderer.invoke('copy-mesh-to-project', srcPath),
  createProjectFromMesh: (opts) => ipcRenderer.invoke('create-project-from-mesh', opts),
  flashTaskbar: () => ipcRenderer.invoke('flash-taskbar'),
  checkGPU: () => ipcRenderer.invoke('check-gpu'),
  checkRAM: () => ipcRenderer.invoke('check-ram'),
  setRamLimit: (pct) => ipcRenderer.invoke('set-ram-limit', pct),
  setGpuLimits: (limits) => ipcRenderer.invoke('set-gpu-limits', limits),
  showInExplorer: (filePath) => ipcRenderer.invoke('show-in-explorer', filePath),
  deleteImageFolder: (folderPath) => ipcRenderer.invoke('delete-image-folder', folderPath),
  importImage: () => ipcRenderer.invoke('import-image'),
  deleteFile: (filePath) => ipcRenderer.invoke('delete-file', filePath),
  deleteProject: (opts) => ipcRenderer.invoke('delete-project', opts),
  onAppCloseRequested: (cb) => ipcRenderer.on('app-close-requested', () => cb()),
  confirmAppClose: () => ipcRenderer.send('app-close-confirmed'),
  openLogsFolder: () => ipcRenderer.invoke('open-logs-folder'),
  calibRun: (opts) => ipcRenderer.invoke('calib-run', opts || {}),
  calibLastReport: () => ipcRenderer.invoke('calib-last-report'),
  calibOpenReport: (opts) => ipcRenderer.invoke('calib-open-report', opts || {}),
  calibListReports: () => ipcRenderer.invoke('calib-list-reports'),
  calibDiagnose: (opts) => ipcRenderer.invoke('calib-diagnose', opts || {}),
  calibTiered: () => ipcRenderer.invoke('calib-tiered'),
  calibV3: (opts = {}) => ipcRenderer.invoke('calib-v3', opts),
  calibCancel: () => ipcRenderer.invoke('calib-cancel'),
  calibReadLog: (opts) => ipcRenderer.invoke('calib-read-log', opts || {}),
  calibClearLog: () => ipcRenderer.invoke('calib-clear-log'),
  onCalibProgress: (cb) => ipcRenderer.on('calib-progress', (e, data) => cb(data)),
  countPython: () => ipcRenderer.invoke('count-python'),
  readLogTail: (opts) => ipcRenderer.invoke('read-log-tail', opts),
  rendererLog: (opts) => ipcRenderer.invoke('renderer-log', opts),
  onMainLog: (cb) => ipcRenderer.on('main-log', (e, data) => cb(data)),
  saveThumbnail: (opts) => ipcRenderer.invoke('save-thumbnail', opts),
  getThumbnail: (meshPath) => ipcRenderer.invoke('get-thumbnail', meshPath),
  removeBackground: (imagePath) => ipcRenderer.invoke('remove-background', imagePath),
  imageAdjust: (opts) => ipcRenderer.invoke('image-adjust', opts),
  saveImageDataUrl: (opts) => ipcRenderer.invoke('save-image-data-url', opts),
  importImageFile: (filePath) => ipcRenderer.invoke('import-image-file', filePath),
  showNotification: (opts) => ipcRenderer.invoke('show-notification', opts),
  exportToUnreal: (opts) => ipcRenderer.invoke('export-to-unreal', opts),
  autoRig: (opts) => ipcRenderer.invoke('auto-rig', opts),
  autoRigAI: (opts) => ipcRenderer.invoke('auto-rig-ai', opts),
  listRigTemplates: () => ipcRenderer.invoke('list-rig-templates'),
  listRigAnimations: (opts) => ipcRenderer.invoke('list-rig-animations', opts),
  saveLandmarks: (opts) => ipcRenderer.invoke('save-landmarks', opts),
  loadLandmarks: (opts) => ipcRenderer.invoke('load-landmarks', opts),
  analyzeSkeleton: (opts) => ipcRenderer.invoke('analyze-skeleton', opts),
  cancelJob: (jobId) => ipcRenderer.invoke('cancel-job', jobId),
  stopSdxlServer: () => ipcRenderer.invoke('stop-sdxl-server'),
  toggleUnrestricted: (opts) => ipcRenderer.invoke('toggle-unrestricted', opts),
  getParentalStatus: () => ipcRenderer.invoke('get-parental-status'),
  checkProjectNsfw: (opts) => ipcRenderer.invoke('check-project-nsfw', opts),
  checkImagesNsfwTags: (opts) => ipcRenderer.invoke('check-images-nsfw-tags', opts),
  getNsfwKeywords: () => ipcRenderer.invoke('get-nsfw-keywords'),
  checkImageNsfw: (opts) => ipcRenderer.invoke('check-image-nsfw', opts),
  batchCheckNsfw: (opts) => ipcRenderer.invoke('batch-check-nsfw', opts),
  img2img: (opts) => ipcRenderer.invoke('img2img', opts),
  autoInpaint: (opts) => ipcRenderer.invoke('auto-inpaint', opts),
  maskInpaint: (opts) => ipcRenderer.invoke('mask-inpaint', opts),
  listImageVersions: (imagePath) => ipcRenderer.invoke('list-image-versions', imagePath),
  revertImage: (opts) => ipcRenderer.invoke('revert-image', opts),
  imageQuickEdit: (opts) => ipcRenderer.invoke('image-quick-edit', opts)
});
