const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('meshyAPI', {
  generateFromPrompt: (opts) => ipcRenderer.invoke('generate-from-prompt', opts),
  generateFromImage: (opts) => ipcRenderer.invoke('generate-from-image', opts),
  generateImages: (opts) => ipcRenderer.invoke('generate-images', opts),
  generateBuildStages: (opts) => ipcRenderer.invoke('generate-build-stages', opts),
  imageToTrellis: (opts) => ipcRenderer.invoke('image-to-3d-trellis', opts),
  imageTo3D: (opts) => ipcRenderer.invoke('image-to-3d', opts),
  onAI3DProgress: (cb) => ipcRenderer.on('ai3d-progress', (e, msg) => cb(msg)),
  onBuildStageProgress: (cb) => ipcRenderer.on('build-stage-progress', (e, data) => cb(data)),
  refineMesh: (opts) => ipcRenderer.invoke('refine-mesh', opts),
  saveScreenshot: (opts) => ipcRenderer.invoke('save-screenshot', opts),
  getVersions: (name) => ipcRenderer.invoke('get-versions', name),
  revertToVersion: (opts) => ipcRenderer.invoke('revert-to-version', opts),
  listProjects: () => ipcRenderer.invoke('list-projects'),
  getConfig: () => ipcRenderer.invoke('get-config'),
  setBlenderPath: () => ipcRenderer.invoke('set-blender-path'),
  runBlenderScript: (opts) => ipcRenderer.invoke('run-blender-script', opts),
  listMeshes: () => ipcRenderer.invoke('list-meshes'),
  getMeshPath: (filename) => ipcRenderer.invoke('get-mesh-path', filename),
  deleteMesh: (filename) => ipcRenderer.invoke('delete-mesh', filename),
  openMeshesFolder: () => ipcRenderer.invoke('open-meshes-folder'),
  openImagesFolder: () => ipcRenderer.invoke('open-images-folder'),
  listImageFolders: () => ipcRenderer.invoke('list-image-folders'),
  readMeshFile: (filePath) => ipcRenderer.invoke('read-mesh-file', filePath),
  getMeshLocalUrl: (filePath) => ipcRenderer.invoke('get-mesh-local-url', filePath),
  exportMesh: (opts) => ipcRenderer.invoke('export-mesh', opts),
  importMesh: () => ipcRenderer.invoke('import-mesh'),
  copyMeshToProject: (srcPath) => ipcRenderer.invoke('copy-mesh-to-project', srcPath),
  createProjectFromMesh: (opts) => ipcRenderer.invoke('create-project-from-mesh', opts),
  flashTaskbar: () => ipcRenderer.invoke('flash-taskbar'),
  checkGPU: () => ipcRenderer.invoke('check-gpu'),
  showInExplorer: (filePath) => ipcRenderer.invoke('show-in-explorer', filePath),
  deleteImageFolder: (folderPath) => ipcRenderer.invoke('delete-image-folder', folderPath),
  importImage: () => ipcRenderer.invoke('import-image'),
  deleteFile: (filePath) => ipcRenderer.invoke('delete-file', filePath),
  saveThumbnail: (opts) => ipcRenderer.invoke('save-thumbnail', opts),
  getThumbnail: (meshPath) => ipcRenderer.invoke('get-thumbnail', meshPath),
  removeBackground: (imagePath) => ipcRenderer.invoke('remove-background', imagePath),
  imageAdjust: (opts) => ipcRenderer.invoke('image-adjust', opts),
  saveImageDataUrl: (opts) => ipcRenderer.invoke('save-image-data-url', opts),
  importImageFile: (filePath) => ipcRenderer.invoke('import-image-file', filePath),
  showNotification: (opts) => ipcRenderer.invoke('show-notification', opts),
  exportToUnreal: (opts) => ipcRenderer.invoke('export-to-unreal', opts),
  autoRig: (opts) => ipcRenderer.invoke('auto-rig', opts),
  listRigTemplates: () => ipcRenderer.invoke('list-rig-templates'),
  cancelJob: (jobId) => ipcRenderer.invoke('cancel-job', jobId),
  img2img: (opts) => ipcRenderer.invoke('img2img', opts),
  autoInpaint: (opts) => ipcRenderer.invoke('auto-inpaint', opts),
  listImageVersions: (imagePath) => ipcRenderer.invoke('list-image-versions', imagePath),
  revertImage: (opts) => ipcRenderer.invoke('revert-image', opts)
});
