"""FabMesh — vehicle-aware sheet runner (ControlNet Depth).

Replaces fabmesh_sheet_runner.py's OpenPose conditioning (character-only)
with Depth conditioning from rendered Hi3DGen mesh depth maps. Works
for ANY subject: vehicles, objects, characters.

Pipeline:
  1. Hi3DGen mesh + 6 strict orthogonal cameras → 6 depth maps
     (already generated by scripts/mv_render_from_mesh.py).
  2. Compose 3×2 sheet of depth maps as ControlNet conditioning.
  3. SDXL + ControlNet Depth + IPAdapter (source photo) renders the
     1536×1024 sheet in ONE pass → native colour/lighting consistency
     across views.
  4. Split sheet into 6 strict orthographic views.

Layout (matches fabmesh_sheet_runner.py):
    row 0:  front (0,0)   | right (90,0)  | back (180,0)
    row 1:  left  (270,0) | top   (0,+90) | bottom (0,-90)

Usage:
    python sheet_render_depth.py <mesh.glb> <source_photo> <out_dir>
        [--steps 30] [--guidance 7.0] [--seed 42]
        [--cn-scale 0.85] [--ip-scale 0.65]
"""
from __future__ import annotations
import os
import sys
import json
import time
import argparse
import numpy as np
from PIL import Image
import torch

SCRIPTS = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(SCRIPTS)
sys.path.insert(0, SCRIPTS)


CELL = 512
COLS = 3
ROWS = 2
SHEET_W = COLS * CELL
SHEET_H = ROWS * CELL

CELL_LAYOUT = [
    (0, 0,   0.0,    0.00, 'front'),
    (1, 0,  90.0,    0.00, 'right'),
    (2, 0, 180.0,    0.00, 'back'),
    (0, 1, 270.0,    0.00, 'left'),
    (1, 1,   0.0,   89.99, 'top'),
    (2, 1,   0.0,  -89.99, 'bottom'),
]


def log(msg):
    print(f'[sheet_depth] {msg}', flush=True)


def _ensure_renders(mesh_path, out_dir, res=CELL):
    """Run mv_render_from_mesh.py if depth maps not present."""
    needed = [os.path.join(out_dir, f'depth_{i}.png') for i in range(6)]
    if all(os.path.isfile(p) for p in needed):
        log(f'depth maps already present in {out_dir}')
        return
    log(f'rendering depth maps via mv_render_from_mesh.py at {res}px...')
    import subprocess
    r = subprocess.run(
        [sys.executable,
         os.path.join(SCRIPTS, 'mv_render_from_mesh.py'),
         mesh_path, out_dir, '--res', str(res)],
        check=False)
    if r.returncode != 0:
        raise RuntimeError(f'mesh render failed: rc={r.returncode}')


def _compose_depth_sheet(out_dir):
    """3×2 sheet of depth maps."""
    sheet = Image.new('RGB', (SHEET_W, SHEET_H), (0, 0, 0))
    for col, row, _, _, label in CELL_LAYOUT:
        idx = next(i for i, (c, r, *_) in enumerate(CELL_LAYOUT)
                   if (c, r) == (col, row))
        p = os.path.join(out_dir, f'depth_{idx}.png')
        d = Image.open(p).convert('L').resize((CELL, CELL), Image.LANCZOS)
        d_rgb = Image.merge('RGB', (d, d, d))
        sheet.paste(d_rgb, (col * CELL, row * CELL))
    return sheet


def _compose_mask_sheet(out_dir):
    """3×2 sheet of subject masks (alpha from view_*.png)."""
    sheet = Image.new('L', (SHEET_W, SHEET_H), 0)
    for col, row, _, _, label in CELL_LAYOUT:
        idx = next(i for i, (c, r, *_) in enumerate(CELL_LAYOUT)
                   if (c, r) == (col, row))
        v = Image.open(os.path.join(out_dir, f'view_{idx}.png')).convert('RGBA')
        v = v.resize((CELL, CELL), Image.LANCZOS)
        a = v.split()[3]
        sheet.paste(a, (col * CELL, row * CELL))
    return sheet


def load_pipeline():
    from diffusers import (
        ControlNetModel,
        StableDiffusionXLControlNetPipeline,
    )
    from transformers import CLIPVisionModelWithProjection
    log('loading RealVisXL + ControlNet Depth + IPAdapter...')
    image_encoder = CLIPVisionModelWithProjection.from_pretrained(
        'h94/IP-Adapter', subfolder='models/image_encoder',
        torch_dtype=torch.float16)
    controlnet = ControlNetModel.from_pretrained(
        'diffusers/controlnet-depth-sdxl-1.0', torch_dtype=torch.float16)
    pipe = StableDiffusionXLControlNetPipeline.from_pretrained(
        'SG161222/RealVisXL_V4.0',
        controlnet=controlnet,
        torch_dtype=torch.float16, variant='fp16',
        use_safetensors=True,
        image_encoder=image_encoder)
    pipe.unet.to(torch.float16)
    pipe.vae.to(torch.float16)
    pipe.text_encoder.to(torch.float16)
    pipe.text_encoder_2.to(torch.float16)
    pipe.load_ip_adapter(
        'h94/IP-Adapter', subfolder='sdxl_models',
        weight_name='ip-adapter-plus_sdxl_vit-h.safetensors')
    pipe.enable_model_cpu_offload()
    log('pipeline ready')
    return pipe


def split_sheet_to_views(sheet_img, mask_sheet, out_dir):
    """Crop the 1536×1024 generated sheet into 6 1024² views.
    Upscale each cell from 512 to 1024 (Lanczos).

    We DO NOT apply the depth-render mesh silhouette as alpha — the
    Hi3DGen silhouette contains holes/noise that would fragment the
    SDXL-painted car. The bake step (hi3dgen_invuv_bake_v3.py) does
    its own masking via inv-UV rasterisation, so only mesh-covered
    pixels reach the atlas regardless of any out-of-silhouette
    content (shadows, halo) in the cell."""
    out_size = 1024
    for col, row, azim, elev, label in CELL_LAYOUT:
        idx = next(i for i, (c, r, *_) in enumerate(CELL_LAYOUT)
                   if (c, r) == (col, row))
        crop = sheet_img.crop((col * CELL, row * CELL,
                                (col + 1) * CELL, (row + 1) * CELL))
        crop = crop.resize((out_size, out_size), Image.LANCZOS)
        rgba = crop.convert('RGBA')
        # Full opaque alpha — bake handles real masking via inv_uv.
        rgba.putalpha(Image.new('L', (out_size, out_size), 255))
        rgba.save(os.path.join(out_dir, f'view_{idx}.png'))
        log(f'  view_{idx} {label:<7} az={azim:+04.0f} el={elev:+04.0f} saved')


def write_views_json(out_dir):
    views = []
    for col, row, azim, elev, label in CELL_LAYOUT:
        idx = next(i for i, (c, r, *_) in enumerate(CELL_LAYOUT)
                   if (c, r) == (col, row))
        views.append({
            'slot': idx,
            'file': f'view_{idx}.png',
            'azim': float(azim),
            'elev': float(elev),
            'label': label,
        })
    with open(os.path.join(out_dir, 'views.json'), 'w', encoding='utf-8') as f:
        json.dump({
            'engine': 'sheet-depth',
            'projection': 'perspective_fov50',
            'note': 'Generated as a 3x2 turnaround sheet via SDXL+ControlNet '
                    'Depth and split into 6 cells.',
            'views': views,
        }, f, indent=2)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('mesh')
    ap.add_argument('source')
    ap.add_argument('out_dir')
    ap.add_argument('--prompt', default=
        'isolated red sports car, photorealistic, glossy paint, '
        'chrome trim, studio lighting, plain white background, '
        'orthographic view, no perspective, model sheet, '
        'turnaround chart, 6 view orthographic projection, '
        'same identical car in each cell')
    ap.add_argument('--negative', default=
        'blurry, distorted, multiple cars, perspective distortion, '
        'shadow, ground reflection, text, watermark, low quality')
    ap.add_argument('--steps', type=int, default=30)
    ap.add_argument('--guidance', type=float, default=7.0)
    ap.add_argument('--cn-scale', type=float, default=0.85)
    ap.add_argument('--ip-scale', type=float, default=0.65)
    ap.add_argument('--seed', type=int, default=42)
    args = ap.parse_args()

    os.makedirs(args.out_dir, exist_ok=True)

    t0 = time.time()
    _ensure_renders(args.mesh, args.out_dir, res=CELL)

    log(f'composing depth sheet ({SHEET_W}x{SHEET_H})...')
    depth_sheet = _compose_depth_sheet(args.out_dir)
    depth_sheet.save(os.path.join(args.out_dir, 'sheet_depth.png'))
    mask_sheet = _compose_mask_sheet(args.out_dir)
    mask_sheet.save(os.path.join(args.out_dir, 'sheet_mask.png'))

    pipe = load_pipeline()
    pipe.set_ip_adapter_scale(args.ip_scale)
    ref = Image.open(args.source).convert('RGB')
    gen = torch.Generator('cuda').manual_seed(args.seed)

    log(f'generating sheet (steps={args.steps}, cfg={args.guidance}, '
        f'cn={args.cn_scale}, ip={args.ip_scale})...')
    t_gen = time.time()
    result = pipe(
        prompt=args.prompt, negative_prompt=args.negative,
        image=depth_sheet,
        ip_adapter_image=ref,
        controlnet_conditioning_scale=args.cn_scale,
        num_inference_steps=args.steps,
        guidance_scale=args.guidance,
        width=SHEET_W, height=SHEET_H,
        generator=gen,
    )
    sheet = result.images[0]
    sheet.save(os.path.join(args.out_dir, 'sheet_output.png'))
    log(f'sheet generated in {time.time()-t_gen:.1f}s')

    log('splitting sheet into 6 views...')
    split_sheet_to_views(sheet, mask_sheet, args.out_dir)
    write_views_json(args.out_dir)

    log(f'DONE in {time.time()-t0:.1f}s -> {args.out_dir}')


if __name__ == '__main__':
    main()
